### ISSUE TITLE
Doesn't work for elysium mod items

### ISSUE THREAD

**Issue by RCXcrafter** [TheLMiffy1111/OreDictionaryInitializer#1]
[The elysium](https://minecraft.curseforge.com/projects/the-elysium) is one of the many mods that doesn't properly add its items to the ore dictionary so I thought I would lfix that with this mod but that doesn't work.

This is what I tried:
blockSulfur-elysium-tile.blockSulphur-0

I did make sure that your mod works on other items.

**Comment by TheLMiffy1111** [comment]
Turns out the creators of Elysium were stupid and registered their blocks in the init stage...  Therefore I don't think I can fix this, since this mod is about registering oreDict entries before the init stage happens.

**Comment by TheLMiffy1111** [comment]
Ok, found a possible fix, decided to make a new version of this mod that does the registering in init

**Comment by TheLMiffy1111** [comment]
Made a version that works

**Comment by RCXcrafter** [comment]
Thanks, this completely fixed all issues I was having. I expected this fix to cause other issues but that didn't happen so that's good.
