### ISSUE TITLE
The mod makes me crash :(

### ISSUE THREAD

**Issue by Migmag789** [TheLMiffy1111/OreDictionaryInitializer#3]
Hey ! I was launching my modpack and it crashed. The crash said that was OreDictInit. Please help me fixing it :)
[crash-2018-10-06_17.47.17-client.txt](https://github.com/TheLMiffy1111/OreDictionaryInitializer/files/2453167/crash-2018-10-06_17.47.17-client.txt)

**Comment by TheLMiffy1111** [comment]
Update exnihilocreatio for now.
Also, this is a JAOPCA issue.

**Comment by Migmag789** [comment]
Oh, ok thank you ^^
